
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.pruebaspractica1compiladores.Parcer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESERVATE_WORD_GRAPHIC = 3;
  public static final int PARENTECIS_APERTURA = 20;
  public static final int PARENTECIS_CIERRE = 21;
  public static final int SUMA = 16;
  public static final int MULTI = 18;
  public static final int SHAPE_CIR = 9;
  public static final int ERROR = 2;
  public static final int COLOR = 7;
  public static final int SHAPE_LIN = 12;
  public static final int RESERVATE_WORD_REFERENCE = 6;
  public static final int SHAPE_REC = 11;
  public static final int COMA = 15;
  public static final int ANIMATION = 8;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int SHAPE_POL = 13;
  public static final int DIV = 19;
  public static final int SHAPE_CUA = 10;
  public static final int error = 1;
  public static final int RESERVATE_WORD_ANIMATION = 4;
  public static final int RESTA = 17;
  public static final int RESERVATE_WORD_OBJECT = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ERROR",
  "RESERVATE_WORD_GRAPHIC",
  "RESERVATE_WORD_ANIMATION",
  "RESERVATE_WORD_OBJECT",
  "RESERVATE_WORD_REFERENCE",
  "COLOR",
  "ANIMATION",
  "SHAPE_CIR",
  "SHAPE_CUA",
  "SHAPE_REC",
  "SHAPE_LIN",
  "SHAPE_POL",
  "NUMBER",
  "COMA",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIV",
  "PARENTECIS_APERTURA",
  "PARENTECIS_CIERRE"
  };
}

