
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COLOR = 3;
  public static final int PARENTECIS_CIERRE = 13;
  public static final int COMA = 7;
  public static final int SUMA = 8;
  public static final int MULTI = 10;
  public static final int NUMBER = 6;
  public static final int SHAPE = 5;
  public static final int EOF = 0;
  public static final int DIV = 11;
  public static final int ANIMATION = 4;
  public static final int error = 1;
  public static final int PARENTECIS_APERTURA = 12;
  public static final int RESTA = 9;
  public static final int RESERVATE_WORD = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RESERVATE_WORD",
  "COLOR",
  "ANIMATION",
  "SHAPE",
  "NUMBER",
  "COMA",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIV",
  "PARENTECIS_APERTURA",
  "PARENTECIS_CIERRE"
  };
}

